#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x12(
        KC_GESC, KC_Q,          KC_W,          KC_E,          KC_R,          KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_GESC,
        KC_TAB,  KC_A,          KC_S,          KC_D,          KC_F,          KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_ENT,
        KC_LSFT, KC_Z,          KC_X,          KC_C,          KC_V,          KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
        KC_NO,   KC_NO,         KC_NO,         MO(2),         MO(1),         KC_BSPC, KC_SPC,  OSL(1),  OSL(2),  KC_NO,   KC_NO,   KC_NO),
	[1] = LAYOUT_ortho_4x12(
        KC_NO,   KC_NO,         KC_NO,         KC_UP,         KC_CAPS,       KC_NO,   KC_NO,   KC_1,    KC_2,    KC_3,    KC_NO,   KC_NO,
        KC_NO,   KC_APP,        KC_LEFT,       KC_DOWN,       KC_RGHT,       KC_HOME, KC_END,  KC_4,    KC_5,    KC_6,    KC_DOT,  KC_TRNS,
        KC_TRNS, OSM(MOD_LALT), OSM(MOD_LSFT), OSM(MOD_LGUI), OSM(MOD_LCTL), KC_PGDN, KC_PGUP, KC_7,    KC_8,    KC_9,    KC_0,    KC_TRNS,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_TRNS,       KC_DEL,  KC_TRNS, KC_TRNS, MO(4),   KC_NO,   KC_NO,   KC_NO),
	[2] = LAYOUT_ortho_4x12(
        KC_GRV,  KC_EXLM,       KC_AT,         KC_HASH,       KC_DLR,        KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_MINS, KC_EQL,  KC_BSLS,
        RESET,   KC_NO,         KC_NO,         KC_LPRN,       KC_RPRN,       KC_NO,   KC_NO,   KC_LCBR, KC_RCBR, KC_UNDS, KC_PLUS, KC_PIPE,
        KC_TRNS, KC_NO,         KC_NO,         KC_LBRC,       KC_RBRC,       KC_NO,   KC_NO,   KC_QUOT, KC_DQUO, KC_NO,   KC_NO,   KC_TRNS,
        KC_NO,   KC_NO,         KC_NO,         KC_TRNS,       KC_NO,         KC_TRNS, KC_TRNS, MO(3),   KC_TRNS, KC_NO,   KC_NO,   KC_NO),
	[3] = LAYOUT_ortho_4x12(
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_TRNS, KC_NO,   KC_NO,   KC_NO,   KC_NO),
	[4] = LAYOUT_ortho_4x12(
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,   KC_NO,   KC_NO,   KC_TRNS, KC_NO,   KC_NO,   KC_NO)
};
